# Konfiguracja bazy danych H2 (w pamięci)
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Konfiguracja JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.h2.console.enabled=true

# Konfiguracja Thymeleaf
spring.thymeleaf.cache=false

# Port aplikacji
server.port=8080
